### ISSUE TITLE
g sfg sfgfsg fs gd

### ISSUE THREAD

**Issue by chickeeen** [ProgramistaZpolski/kasztanlang#1]
php to zlo
dzisiaj napisze lepszy kasztanlang hhhhhhhhhh

**Comment by ProgramistaZpolski** [comment]
Nie zgadzam się, php to dobro.

**Comment by chickeeen** [comment]
bo jestes zjebem, php to zlo

**Comment by ProgramistaZpolski** [comment]
Ale php to nie jest zło

**Comment by chickeeen** [comment]
php to zło
twoj stary to inwalida wali smiglo na wozku inwalidzkim
wgl Compiler XD
